"""Tests for timestamp normalization of generated files."""

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

try:
    from . import _bootstrap  # noqa: F401  (python -m unittest discover -s tests -t .)
except ImportError:
    import _bootstrap  # noqa: F401  (python -m unittest discover -s tests)

from kicad_library_automation.modules.reproducible import normalize_outputs

GERBER = (
    "%TF.GenerationSoftware,KiCad,Pcbnew,9.0.2*%\n"
    "%TF.CreationDate,{date}+02:00*%\n"
    "%TF.ProjectId,demo,64656d6f,rev?*%\n"
    "G04 Created by KiCad (PCBNEW 9.0.2) date {date2}*\n"
    "%MOMM*%\n"
)
DRILL = "M48\n; DRILL file {{KiCad 9.0.2}} date {date}\n; FORMAT={{-:-/ absolute / metric / decimal}}\n; #@! TF.CreationDate,{date}+02:00\nFMAT,2\n"
SVG = '<svg>\n<title>SVG Image created as demo.svg date {date} </title>\n<desc>Image generated by PCBNEW </desc>\n</svg>\n'
STEP = "HEADER;\nFILE_NAME('demo.step','{date}',('Pcbnew'),('Kicad'),\n'Open CASCADE STEP processor 7.8','KiCad to STEP converter','Unknown');\n"
GBRJOB = '{{\n  "Header": {{\n    "GenerationSoftware": {{\n      "Vendor": "KiCad"\n    }},\n    "CreationDate": "{date}+02:00"\n  }}\n}}\n'
PDF = "%PDF-1.5\n1 0 obj\n<<\n/Producer (KiCad PDF)\n/CreationDate (D:{pdfdate})\n>>\nendobj\nxref\n"


def _write(root: Path, date: str) -> None:
    (root / "g").mkdir(parents=True, exist_ok=True)
    (root / "g" / "demo-F_Cu.gtl").write_text(GERBER.format(date=date, date2=date.replace("T", " ")), encoding="utf-8")
    (root / "g" / "demo-job.gbrjob").write_text(GBRJOB.format(date=date), encoding="utf-8")
    (root / "demo.drl").write_text(DRILL.format(date=date), encoding="utf-8")
    (root / "demo.svg").write_text(SVG.format(date=date), encoding="utf-8")
    (root / "demo.step").write_text(STEP.format(date=date), encoding="utf-8")
    (root / "demo.pdf").write_bytes(PDF.format(pdfdate=date.replace("-", ":").replace("T", ":")).encode())
    (root / "keep.csv").write_text("created on {date}\n".format(date=date), encoding="utf-8")


def _snapshot(root: Path) -> dict:
    return {p.relative_to(root).as_posix(): p.read_bytes() for p in sorted(root.rglob("*")) if p.is_file()}


class ReproducibleTests(unittest.TestCase):
    def test_outputs_with_different_dates_become_identical(self) -> None:
        with tempfile.TemporaryDirectory() as a, tempfile.TemporaryDirectory() as b:
            ra, rb = Path(a), Path(b)
            _write(ra, "2026-01-01T10:00:00")
            _write(rb, "2026-02-03T11:22:33")
            normalize_outputs([ra, rb])
            sa, sb = _snapshot(ra), _snapshot(rb)
            for name in sa:
                if name == "keep.csv":
                    self.assertNotEqual(sa[name], sb[name], "CSV content must not be touched")
                    continue
                self.assertEqual(sa[name], sb[name], name)
                self.assertNotIn(b"2026", sa[name], name)

    def test_pdf_length_is_preserved(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _write(root, "2026-01-01T10:00:00")
            before = (root / "demo.pdf").stat().st_size
            normalize_outputs(root / "demo.pdf")
            self.assertEqual((root / "demo.pdf").stat().st_size, before)

    def test_normalization_is_idempotent(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            _write(root, "2026-01-01T10:00:00")
            normalize_outputs(root)
            self.assertEqual(normalize_outputs(root), [])


if __name__ == "__main__":
    unittest.main()
